name: ozi-publish
description: "OZI publish action."
inputs:
  github-token:
    description: "GitHub workflow-generated token."
    required: true
  create-pull-request:
    description: "Create a pull request on the default branch."
    default: false
  pull-request-body:
    description: "Text to use for the pull request body."
    default: "Created automatically. Manually close and reopen to enable checks."
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093

    - name: Move artifact
      run: cp -a artifact/. ./
      shell: bash

    - name: Publish package distributions to GitHub Releases
      uses: python-semantic-release/publish-action@e5e3010f6a207cd5d6f5d3dccedbea355484ca02
      with:
        github_token: ${{ inputs.github-token }}

    - name: Get HEAD branch name
      id: head
      if: ${{ fromJSON(inputs.create-pull-request) == true }}
      run: git remote show origin | grep 'HEAD branch' | cut -d ":" -f2 | sed 's/ /name=/' >> $GITHUB_OUTPUT
      shell: bash

    - if: ${{ fromJSON(inputs.create-pull-request) == true && steps.head.outputs.name == github.ref_name }}
      run: echo 'already in HEAD branch no pull request will be created'
      shell: bash

    - name: Create pull request
      if: ${{ fromJSON(inputs.create-pull-request) == true && steps.head.outputs.name != github.ref_name }}
      run: gh pr create -B $HEAD_BRANCH -H $REF_NAME --title "Merge $REF_NAME into $HEAD_BRANCH" --body "$PR_BODY"
      env:
          HEAD_BRANCH: ${{ steps.head.outputs.name }}
          REF_NAME: ${{ github.head_ref || github.ref_name }}
          PR_BODY: ${{ inputs.pull-request-body }}
          GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
